#!/usr/bin/env python

import sys
import os
import subprocess
import json
from enum import IntEnum
from pprint import pprint

# dependencies
#   - bitwarden-cli  (authenticated once using apisecret)
#   - keyctl
#   - at

# config

EMAIL = "joseph@holten.com"
method = 3
AUTO_LOCK = 900
AUTO_LOGOUT = 120   # in minutes

def bw_status(session_key=""):
    if session_key:
        output = subprocess.run(['bw', 'status', '--session', session_key], capture_output=True, text=True)
        #print(output)
        return json.loads(output.stdout)
    
    output = subprocess.run(['bw', 'status'], capture_output=True, text=True)
    #print(output)
    return json.loads(subprocess.run(['bw', 'status'], capture_output=True, text=True).stdout)

def all_unique(container):
    return len(container) == len(set(container))

status = bw_status()

session_key = ""

if status['status'] == 'unlocked':
    session_key = os.environ.get('BW_SESSION')
    print("Vault unlocked!", file=sys.stderr)

else:
    # try to find session key in keyctl 
    output = subprocess.run(["keyctl", "request", "user", "bw_session"], capture_output=True, text=True)

    # session key available
    if not output.stderr and output.stdout.rstrip("\n").isdigit():  
        key_id = output.stdout.rstrip("\n")
        output = subprocess.run(["keyctl", "print", key_id], capture_output=True, text=True)

        session_key = output.stdout.rstrip("\n")

    # no session key saved with keyctl (i.e. locked or unauthenticated) or session key invalid
    if output.stderr or bw_status(session_key)['status'] != "unlocked":
        # definitely need password
        password = subprocess.run(['rofi', '-dmenu', '-p', 'Master Password', '-password', '-lines' ,'0'], capture_output=True, text=True).stdout
        password = password.rstrip('\n')

        output = None

        if status['status'] == 'unauthenticated':
            code = subprocess.run(['rofi', '-dmenu','-p', 'YubiKey 2FA code', '-password', '-lines' ,'0'], capture_output=True, text=True).stdout.rstrip("\n")
            output = subprocess.run(['bw', 'login', 'joseph@holten.com', password, '--method', '3', '--code', code, "--raw"], capture_output=True, text=True)
            
            if not output.stdout.startswith('You are logged in!'):   # failed at logging in
                print("Error logging in: ", output, file=sys.stderr)
                exit(1)

            print("Logged into vault", file=sys.stderr)


        elif status['status'] == 'locked':
            output = subprocess.run(["bw", "unlock", password, "--raw"], capture_output=True, text=True) 
            print("Unlocked vault", file=sys.stderr)

        else:
            assert False, f"Unhandled status {status}"

        session_key = output.stdout.rstrip("\n")

    else:
        print("Success getting session_key from keyctl, session_key is", session_key, file=sys.stderr)



# register session_key with keyctl
output = subprocess.run(["keyctl", "add", "user", "bw_session", session_key, "@u"], capture_output=True, text=True)
key_id = output.stdout.rstrip("\n")
output = subprocess.run(["keyctl", "timeout", key_id, str(AUTO_LOCK)], capture_output=True, text=True)

# deschedule old logout
output = subprocess.run(["keyctl", "request", "user", "bw_logout"], capture_output=True, text=True)
if output.stdout.rstrip("\n").isdigit():  # have gotten a key_id
    # remove pending logout
    key_id = output.stdout.rstrip("\n")
    output = subprocess.run(["keyctl", "print", key_id], capture_output=True, text=True)
    job_id = output.stdout.rstrip("\n")

    output = subprocess.run(["atrm", job_id], capture_output=True, text=True)


elif output.stderr != "request_key: Required key not available\n":  # some error, that is not that the job has already been performed
    print("Error rescheduling 'bw logout': couldn't get job_id from keyctl.\nkeyctl error message: ", output, file=sys.stderr)
    exit(1)
            
# MAIN PART

output = subprocess.run(["bw", "list", "items", "--session", session_key], capture_output=True, text=True)
items = json.loads(output.stdout)
items = [ item for item in items if 'login' in item ]  # restrict ourselves to login

rofi_input = [ item['name'] for item in items ]
rofi_input = "\n".join(rofi_input)

output = subprocess.run(f'echo "{rofi_input}" | rofi -dmenu -p BW', capture_output=True, text=True, shell=True)
name = output.stdout.rstrip("\n")
item = list(filter(lambda item: item['name'] == name, items))[0]

subprocess.run(["xdotool", "type", item['login']['username']])
subprocess.run(["xdotool", "key", "Tab"])
subprocess.run(["xdotool", "type", item['login']['password']])

# END MAIN

# schedule new logout
output = subprocess.run(f'echo "bw logout" | at now + {AUTO_LOGOUT} minutes', capture_output=True, text=True, shell=True)
job_id = output.stderr.split("\n")[1].split()[1]
output = subprocess.run(["keyctl", "add", "user", "bw_logout", job_id, "@u"], capture_output=True, text=True)
output = subprocess.run(["keyctl", "timeout", str(AUTO_LOGOUT*60)], capture_output=True, text=True)
